backend:
  name: git-gateway
  branch: main

# Local backend for testing without a server (optional, requires running a separate proxy)
  local_backend: true

media_folder: "static/img/news"
public_folder: "/img/news"

collections:
  - name: "blog"
    label: "–ù–æ–≤–æ—Å—Ç–∏"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "–ó–∞–≥–æ–ª–æ–≤–æ–∫", name: "title", widget: "string"}
      - {label: "–ù–∏–∫–Ω–µ–π–º (–û–±—è–∑–∞—Ç–µ–ª—å–Ω–æ)", name: "nickname", widget: "string", required: true}
      - {label: "–ö–æ–æ—Ä–¥–∏–Ω–∞—Ç—ã", name: "coords", widget: "string", required: false}
      - {label: "–î–∞—Ç–∞ –∏ –≤—Ä–µ–º—è –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è", name: "event_date", widget: "datetime", required: false}
      - {label: "–û–±–ª–æ–∂–∫–∞", name: "image", widget: "image", required: false}
      - {label: "–ó–∞–∫—Ä–µ–ø–∏—Ç—å –ø–æ—Å—Ç (üìå)", name: "pinned", widget: "boolean", default: false, required: false}
      - {label: "–¢–µ–∫—Å—Ç –Ω–æ–≤–æ—Å—Ç–∏ (–î–æ–ø. —Ñ–æ—Ç–æ –¥–æ–±–∞–≤–ª—è–π—Ç–µ —Å—é–¥–∞)", name: "body", widget: "markdown"}
